chore: support local model for running e2e tests
i-am-bee/bee-agent-framework pull request #103
Opened 2024-10-21 15:18 UTC by mhdawson

Add support for using a local model for e2e testing.

### Which issue(s) does this pull-request address?

Currently e2e testing requires a remote service which may cost people $ to run. Add the option
to use a model running locally if OLLAMA_HOST is set. If an API key is specified the associated
service will be used in preference to OLLAMA_HOST so this change should have no effect on
people not trying to use a local model.

### Description

If OLLAMA_HOST is set and no other API keys are providced use that host to run the e2e tests.

### Checklist

- [X] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [X] Linting passes: `yarn lint` or `yarn lint:fix`
- [X] Formatting is applied: `yarn format` or `yarn format:fix`
- [X] Unit tests pass: `yarn test:unit`
- [X] E2E tests pass: `yarn test:e2e`
- [X] Tests are included 
- [X] Documentation is changed or added
- [X] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-10-21 15:22 UTC, mhdawson commented
It takes about 10 minutes for the e2e tests to pass with my local ollama instance with a 4070ti super, but unless I have to debug issues that's better for me than having to use a service where I pay for the requests.

2024-10-21 21:57 UTC, Tomas2D requested changes
The code looks fine, but I'm not sure if we should force people to use `llama3.1:70b-instruct-q5_K_M`. Do you have any ideas?

Also make the function `noTimeoutFetch`  inline so it is automatically typed.

2024-10-22 15:56 UTC, mhdawson commented
@Tomas2D we could read the model from a .env file, however, not all versions work/pass the e2e tests. That was the smallest/lowest quantization that I found worked so there is some value in sharing which model will succeed when running the e2e tests.

2024-10-22 17:19 UTC, Tomas2D requested changes
Are you sure? I was able to pass all E2E tests with ollama3.1:8b

2024-10-22 21:51 UTC, mhdawson commented
@Tomas2D I'll give it a try again, with the smaller models. I had tried a few and seen failures but maybe something else was going on.

2024-10-22 23:14 UTC, mhdawson commented
Not sure what I had wrong when I ran the tests earlier, but super happy that they pass with the smaller model.

Updated to inline as requested, to use llama3.1:8b by default and to use process.env.OLLAMA_MODEL to override it exists./

2024-10-23 22:19 UTC, Tomas2D requested changes
I think that `slow` version is not required. By the way you can set `timeout` in vitest config for e2e tests.

2024-10-23 22:19 UTC, Tomas2D commented on tests/utils/llmFactory.ts
> +        fetch: (input: any, init: any) => {
either add proper types or remove typing completely

2024-10-24 16:35 UTC, mhdawson commented
@Tomas2D updated as requested. I had to work around the problem that the undici RequestInit does not extend the standard fetch one  ( I guess since it does not implement all of the options) but I was using an option not defined in the standard fetch one.

2024-10-24 16:41 UTC, mhdawson commented
Rebasing to pull in the latest seem to results in failures running the e2e tests, but I also tried using OpenAI instead of ollama and got a bunch of failures as well, so I don't think that is related to this PR.

Is there a known issue with the e2e tests or something I need to do beyond rebasing after the addition of the examples to the e2e tests?

2024-10-24 22:18 UTC, Tomas2D commented
The E2E Tests and E2E Examples should be fixed now.

2024-10-24 22:20 UTC, Tomas2D approved these changes

2024-10-25 19:29 UTC, mhdawson commented
@Tomas2D thanks for confirming, rebased.

2024-10-27 04:50 UTC, merged