feat(tools): switch PythonTool and CustomTool to HTTP API
i-am-bee/bee-agent-framework pull request #195
Opened 2024-11-27 03:57 UTC by markstur

### Which issue(s) does this pull-request address?

Part of: #149 

### Description

* Modify the existing PythonTool over gRPC to go over HTTP.
* Add tests (written for gRPC but adapted for the new one).
* Requires CODE_INTERPRETER_URL env var to point to exposed HTTP port (50081).

### Checklist

- [x] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [x] Linting passes: `yarn lint` or `yarn lint:fix`
- [x] Formatting is applied: `yarn format` or `yarn format:fix`
- [x] Unit tests pass: `yarn test:unit`
- [x] E2E tests pass: `yarn test:e2e`
- [x] Tests are included 
- [ ] Documentation is changed or added
- [x] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-12-14 07:33 UTC, markstur commented
Marking as draft because custom tool will also have to be updated.

2024-12-17 15:15 UTC, JanPokorny commented
You could probably remove some of the grpc dependencies together with this PR -- IIRC we use gRPC in a different part of the codebase, but through a different library.

2025-01-09 15:41 UTC, Tomas2D requested changes

2025-01-09 15:41 UTC, Tomas2D commented on src/tools/custom.ts
> +    });
create utility function for fetching as this code block is duplicated

2025-01-09 15:41 UTC, Tomas2D commented on src/tools/python/python.ts
> +      files: this.files,
`files: shallowCopy(this.files)`

2025-01-09 15:41 UTC, Tomas2D commented on src/tools/python/python.ts
> +        .filter((file) => file.path.startsWith(prefix))
filter first

2025-01-10 10:52 UTC, Tomas2D approved these changes

2025-01-10 10:52 UTC, merged