feat(tools): add HumanTool for human intervention during workflows
i-am-bee/bee-agent-framework pull request #203
Opened 2024-11-29 21:41 UTC by matiasmolinas

### Human intervention abstraction - Step 1

Description:
Step 1: Define the 'HumanTool' as a tool which can be equipped to any Bee and be invoked by it when it deems there is some missing information required for the following steps and hence must call out to the user to collect it. So I agree with you on the following:

Tool Name: 'HumanTool'
Tool Input: For a Bee to use this tool, it should generate a NL message asking the user for some specific information.
Tool Output: NL response from the end user
BeeAgentRunner 'HumanTool' Execution: The Runner should then execute the HumanTool by sending the NL message to the end user and wait for a response. Once the user has responded, the tool output (message from the user) is appended to the Agent memory and the loop for Action and ActionInput can continue

Closes: #121 

### Description

This Pull Request introduces the HumanTool to the Bee Agent Framework as part of Step 1 of the issue: Human intervention abstraction - enhancement. The tool enables Bees to interact with users during workflows to gather additional information.

### Changes
1. **Added HumanTool (`src/tools/human.ts`):**
   - Implements a tool to handle user input during workflows.
   - Provides natural language (NL) input and output support.

2. **Extended Bee Prompts (`src/agents/bee/prompts.ts`):**
   - Includes prompts for the HumanTool to integrate seamlessly with Bees.

3. **Added Helper for Console Interaction (`src/helpers/io.ts`):**
   - Provides shared console reading functionality for tools like HumanTool.

4. **Created an Experimental Agent (`examples/agents/experimental/humantool_agent.ts`):**
   - Demonstrates the usage of HumanTool in a real-world workflow scenario.

### Checklist

- [x] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [x] Linting passes: `yarn lint` or `yarn lint:fix`
- [x] Formatting is applied: `yarn format` or `yarn format:fix`
- [ ] Unit tests pass: `yarn test:unit`
- [ ] E2E tests pass: `yarn test:e2e`
- [ ] Tests are included 
- [ ] Documentation is changed or added
- [x] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-12-03 15:03 UTC, Tomas2D requested changes

2024-12-03 20:07 UTC, matiasmolinas commented on examples/agents/experimental/humantool_agent.ts
Ok thanks! working on it

2024-12-05 12:56 UTC, matiasmolinas commented on examples/agents/experimental/humantool_agent.ts
Bullets 1, 2, and 3 are done. Now, I am working on fixing the console reader functionality.

2024-12-05 20:33 UTC, matiasmolinas commented on examples/agents/experimental/humantool_agent.ts
Hi @Tomas2D, I’ve addressed bullets 1, 2, and 3. Regarding the console reader functionality, since it’s already implemented, I want to avoid introducing a new one. Would you prefer that I move the HumanTool into the examples directory so it can rely on the existing console reader there, or is there another approach you’d recommend for reusing the existing console reader in src/? Any guidance on the best path forward would be greatly appreciated.

2024-12-07 08:57 UTC, matiasmolinas commented on examples/agents/experimental/humantool_agent.ts
Hi @Tomas2D,

I will proceed by moving the HumanTool into the examples folder. This approach allows it to rely on the existing console reader implementation without introducing any new dependencies. For now, I’ll treat it as an experimental feature in examples. If, in the future, it becomes more integral, we can revisit centralizing the console reader in src/.

Thanks!

2024-12-07 10:54 UTC, matiasmolinas commented on examples/agents/experimental/humantool_agent.ts
Hi @Tomas2D,

I’ve moved the HumanTool into the examples directory so it now uses the existing console reader implementation without introducing any new dependencies. This should address the requested changes and maintain the minimal working example approach. Please let me know if anything else is needed.

Thanks!

2024-12-13 21:41 UTC, matiasmolinas commented
There is a complex merge and an issue in one commit message that is difficult to fix. I will take the latest files, create a new branch called fresh-human-tool-new, and open a new PR.

2024-12-13 23:30 UTC, closed without merging