docs: add role and tools to getting started cli experience
i-am-bee/bee-agent-framework pull request #211
Opened 2024-12-02 22:31 UTC by psschwei

Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>

### Which issue(s) does this pull-request address?

Closes: #148

### Description

We have found that bees perform best when:
* they use fewer number of tools, and
* they are provided explicit instructions/role

Here we updated the getting started section of the README to incorporate those recommendations into the simple example. We update the system prompt to provide explicit instructions, and we remove the search tool as it isn't needed for weather-related queries. It also adds some tips related to these two points to the appropriate section.

Additionally, it adds a yarn helper method to run the simple example: `yarn run quickstart`

### Checklist

- [x] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [x] Linting passes: `yarn lint` or `yarn lint:fix`
- [x] Formatting is applied: `yarn format` or `yarn format:fix`
- [x] Unit tests pass: `yarn test:unit`
- [x] E2E tests pass: `yarn test:e2e`
- [x] Tests are included 
- [x] Documentation is changed or added
- [x] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

no tests included as this is a documentation change

2024-12-02 22:32 UTC, psschwei commented
FYI @mmurad2 - if this wasn't what you were envisioning let me know, happy to iterate on this

2024-12-02 22:38 UTC, psschwei commented
this is a new one :smile: 

![image](https://github.com/user-attachments/assets/3597fe33-c526-4689-82dc-7417df2cf213)

![image](https://github.com/user-attachments/assets/335a5320-847c-4c01-a9a7-f65378e6760d)

2024-12-03 09:47 UTC, Tomas2D requested changes
I think the issue was about adding `role` and `tools` to the CLI.
So, when someone starts the script, it first asks for tools and a role, and then the chat begins.

2024-12-03 09:47 UTC, Tomas2D commented on README.md
> +➡️ you can run this example after local installation, using the command `yarn run quickstart`
`run` is not needed

2024-12-03 09:47 UTC, Tomas2D commented on README.md
> +➡️ See a more [advanced example](/examples/agents/bee.ts)
Missing `.` at the end.

2024-12-03 09:47 UTC, Tomas2D commented on README.md
> +  },
This definitely should not be part of README. Keep the example as is.

2024-12-03 14:25 UTC, psschwei commented
> I think the issue was about adding `role` and `tools` to the CLI.
> So, when someone starts the script, it first asks for tools and a role, and then the chat begins.

Ok, I think I misunderstood the ask here.

Do we currently have a way to create an agent from the command line? I believe all the examples I saw here are running an existing source code file (e.g. `yarn start examples/agents/bee.ts`) which already have tools and instructions predefined. So I'd assume we'd need to edit the source code files to add the tools / role prior to running the file? Or is there another approach that I'm missing?

Would there be a way to use the API here? That seems like the ideal way to add this kind of functionality, but I'm assuming that would need the whole stack and not just the framework, so might not be an option here...

2024-12-03 14:53 UTC, Tomas2D commented
Why would you use an API in the framework? API is built on top of the framework.
Just ask the user to specify a role, and if one is not provided then fallback to the default. 

Maybe consult details in the related issue.

2024-12-03 14:54 UTC, closed without merging