feat(tools): additional tools in SQL toolkit
i-am-bee/bee-agent-framework pull request #212
Opened 2024-12-03 07:34 UTC by tonxxd

### Which issue(s) does this pull-request address?
https://github.com/i-am-bee/bee-agent-framework/issues/182

### Description
This feature proposal introduces a toolkit for SQL and data analysis, by enhancing current SQL tool and introducing few other concepts

It adds excel and csv support for SQLTool in order to perform advanced querying on these type of files.
It also adds the ability to provide few shot examples for the connect db, useful for bigger complex dbs.

- TODO:
- tests
- improve search values action
- add embedding based schema linker
- correction 

### Checklist

- [x] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [x] Linting passes: `yarn lint` or `yarn lint:fix`
- [x] Formatting is applied: `yarn format` or `yarn format:fix`
- [x] Unit tests pass: `yarn test:unit`
- [x] E2E tests pass: `yarn test:e2e`
- [x] Tests are included 
- [x] Documentation is changed or added
- [x] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-12-03 09:40 UTC, Tomas2D requested changes
Adding the file support (public providers) that internally gets converted to SQL adds extra complexity (initialize method, mutation properties, checks) unrelated to the core SQL functionality.

I would add a static (async) factory method to convert and initiate the SQLTool with the SQLite connection. Something like this.

```
static async fromFile(provider: PublicProvider, ...) {
   // conversion
   return new SQLTool(...)
}
```

2024-12-03 09:40 UTC, Tomas2D commented on examples/agents/data_analyst.ts
> +// });
Either remove or create another example.

2024-12-03 09:40 UTC, Tomas2D commented on examples/agents/data_analyst.ts
> +          "You are the Bee 🐝 Data Agent! If the user asks about data questions, use the FlowPilot tool, passing the user natural language question as 'question' to the tool. Do not render ascii table
I would rather not use emojis.

2024-12-03 09:40 UTC, Tomas2D commented on src/tools/database/metadata.ts
> +function deduplicateAndSortResults(
Consider leveraging functionality from `remeda` library.

2024-12-03 09:40 UTC, Tomas2D commented on src/tools/database/sql.test.ts
> +import { beforeEach, expect, vi } from "vitest";
this line can be removed

2024-12-03 09:40 UTC, Tomas2D commented on src/tools/database/sql.ts
> +  public options: ToolOptions;
Can be removed as it is defined in the parent class.

2024-12-03 09:40 UTC, Tomas2D commented on src/tools/database/sql.ts
> +    this.options = options;
Can be removed as it is defined in the parent class.

2024-12-04 04:39 UTC, tonxxd commented on src/tools/database/vectordb.ts
👍 shall i rebase from that branch?

2024-12-04 11:34 UTC, Tomas2D commented on src/tools/database/vectordb.ts
Not yet.

2024-12-04 16:16 UTC, Tomas2D commented on src/tools/database/vectordb.ts
Just implement the tool without it if possible.

2024-12-11 13:14 UTC, Tomas2D commented on src/tools/database/vectordb.ts
Embedding support has been added. Just rebase.

2025-01-20 19:23 UTC, Tomas2D commented
Closing for inactivity.

2025-01-20 19:23 UTC, closed without merging