Add OpenAPI tool
i-am-bee/bee-agent-framework pull request #246
Opened 2024-12-11 21:46 UTC by akihikokuroda

### Which issue(s) does this pull-request address?

Closes: #105 

### Description

### Checklist

- [ ] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [ ] Linting passes: `yarn lint` or `yarn lint:fix`
- [ ] Formatting is applied: `yarn format` or `yarn format:fix`
- [ ] Unit tests pass: `yarn test:unit`
- [ ] E2E tests pass: `yarn test:e2e`
- [ ] Tests are included 
- [ ] Documentation is changed or added
- [ ] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-12-12 16:36 UTC, Tomas2D requested changes

2024-12-12 23:42 UTC, akihikokuroda commented on src/tools/openapi.ts
> +    url.pathname = join(url.pathname, path);
It doesn't work here.  Params must be embedded in the path in some cases.

2024-12-12 23:43 UTC, akihikokuroda commented on src/tools/openapi.ts
> +    input: any,
So far, I can not make it work here.

2024-12-13 08:08 UTC, Tomas2D requested changes

2024-12-13 08:08 UTC, Tomas2D commented on src/tools/openapi.ts
> +    input: any,
What is the error message?

2024-12-13 08:08 UTC, Tomas2D commented on src/tools/openapi.ts
> +      throw new ToolError(`Request to ${url} failed.`);
If you throw this error without any context, the agent cannot retry. Do this instead.

```ts
} catch (err) {
   throw new ToolError(`Request to ${url} has failed.`, [err]);
}
```

2024-12-13 13:01 UTC, akihikokuroda commented on src/tools/openapi.ts
> +    input: any,
The error is:
```
src/tools/openapi.ts:129:19 - error TS2416: Property '_run' in type 'OpenAPITool' is not assignable to the same property in base type 'Tool<OpenAPIToolOutput, OpenAPIToolOptions, BaseToolRunOptions>'.
  Type '(input: Record<string, any>, _options: Partial<BaseToolRunOptions>, run: GetRunContext<this>) => Promise<OpenAPIToolOutput>' is not assignable to type '(arg: FromSchemaLike<Awaited<ReturnType<this["inputSchema"]>>>, options: Partial<BaseToolRunOptions>, run: GetRunContext<...>) => Promise<...>'.
    Types of parameters 'input' and 'arg' are incompatible.
      Type 'FromSchemaLike<Awaited<ReturnType<this["inputSchema"]>>>' is not assignable to type 'Record<string, any>'.
        Type 'unknown' is not assignable to type 'Record<string, any>'.

129   protected async _run(
```

2024-12-14 10:01 UTC, Tomas2D commented on src/tools/openapi.ts
> +    input: any,
Ohh, I see. You must also do this `inputSchema(): SchemaObject {` then it will work.

2024-12-14 16:17 UTC, akihikokuroda commented on src/tools/openapi.ts
> +    input: any,
Thanks!

2024-12-19 10:06 UTC, Tomas2D commented on src/tools/openapi.ts
> +  protected http_proxy_url?: string;
use `camelCase` in both cases please

2024-12-19 10:06 UTC, Tomas2D commented on src/tools/openapi.ts
> +  beforeFetch: Callback<{ url: string }>;
pass URL instance directly to allow modifications

2024-12-19 10:06 UTC, Tomas2D commented on src/tools/openapi.ts
> +import { parse } from "yaml";
add `yaml` as optional peer dependency

2024-12-20 15:38 UTC, Tomas2D approved these changes

2024-12-20 15:38 UTC, Tomas2D approved these changes
Great work! 🚀

2024-12-20 15:39 UTC, merged