feat(tool): add google custom search tool
i-am-bee/bee-agent-framework pull request #34
Opened 2024-09-26 03:38 UTC by abughali

### Which issue(s) does this pull-request address?

### Description

- Adding Google Custom Search Tool
- Updated Readme

### Checklist

- [x] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [x] Linting passes: `yarn lint` or `yarn lint:fix`
- [x] Formatting is applied: `yarn format` or `yarn format:fix`
- [x] Unit tests pass: `yarn test:unit`
- [x] E2E tests pass: `yarn test:e2e`
- [x] Tests are included 
- [x] Documentation is changed or added
- [x] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-09-26 03:41 UTC, abughali commented
@Tomas2D FYK review

2024-09-26 08:06 UTC, Tomas2D requested changes

2024-09-26 08:06 UTC, Tomas2D commented on src/tools/search/googleCustomSearch.ts
> +    });
Are results somehow sorted?

2024-09-27 16:49 UTC, Tomas2D commented on package.json
> +    "@googleapis/customsearch": "*",
Users should use the version that we developed our extension against. So you might use `^3.2.0` or `^3.0.0` (but test it first if you decide to go with 3.0.0)

2024-09-27 16:50 UTC, Tomas2D commented on src/tools/search/googleCustomSearch.ts
> +  protected cseId: string | undefined;
I think you can change it to

```
  protected apiKey: string;
  protected cseId: string;
```

2024-09-27 17:18 UTC, Tomas2D approved these changes
Great work 🚀

2024-09-27 17:18 UTC, merged