fix: example -updates the examples to the new llama 3.2 3B instruct
i-am-bee/bee-agent-framework pull request #53
Opened 2024-10-02 16:52 UTC by Abiji-2020

### Which issue(s) does this pull-request address?

Closes:  #47 

### Description

The last PR #51  contains many errors due to the standards of the commit message, which was updated in this branch and proper naming is followed. 

### Checklist

- [ ] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [ ] Linting passes: `yarn lint` or `yarn lint:fix`
- [ ] Formatting is applied: `yarn format` or `yarn format:fix`
- [ ] Unit tests pass: `yarn test:unit`
- [ ] E2E tests pass: `yarn test:e2e`
- [ ] Tests are included 
- [ ] Documentation is changed or added
- [ ] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-10-02 17:06 UTC, Abiji-2020 commented
@Tomas2D this is a new PR for the issue #47  as the I had messed up the old PR on the naming issues

2024-10-03 12:39 UTC, Abiji-2020 commented
@Tomas2D any update on the PR?

2024-10-03 14:12 UTC, Tomas2D requested changes

2024-10-03 14:12 UTC, Tomas2D commented on examples/agents/bee_advanced.ts
> +const llm = BAMChatLLM.fromPreset("meta-llama/Llama-3.2-3B-Instruct");
This model does not exist in the BAM environment.

2024-10-03 14:12 UTC, Tomas2D commented on examples/agents/sql.ts
> +  modelId: "llama3.2",
Verify whether the given model exists in GROQ.

2024-10-03 14:12 UTC, Tomas2D commented on examples/llms/providers/watsonx.ts
> +const chatLLM = WatsonXChatLLM.fromPreset("meta-llama/Llama-3.2-3B-Instruct", {
The name is incorrect. The correct one should be `llama-3-2-3b-instruct`.
Please do a test run to ensure whether it works.

2024-10-03 14:12 UTC, Tomas2D commented on examples/llms/providers/watsonx_verbose.ts
> +  modelId: "meta-llama/Llama-3.2-3B-Instruct",
The name is incorrect. The correct one should be `llama-3-2-3b-instruct`.
Please do a test run to ensure whether it works.

2024-10-03 14:12 UTC, Tomas2D commented on src/adapters/bam/chatPreset.ts
> +  "meta-llama/Llama-3.2-3B-Instruct": (): BAMChatLLMPreset => {
Same as above.

2024-10-03 14:12 UTC, Tomas2D commented on package.json
> +  "packageManager": "yarn@4.5.0+sha512.837566d24eec14ec0f5f1411adb544e892b3454255e61fdef8fd05f3429480102806bac7446bc9daff3896b01ae4b62d00096c7e989f1596f2af10b927532f39",
Don't change the version of the package manager. This should not be done in this PR.

2024-10-03 14:12 UTC, Tomas2D commented on src/adapters/shared/llmChatTemplates.ts
> +{{assistant}}<|eot_id|>{{/assistant}}{{/messages}}<|start_header_id|>assistant<|end_header_id|>
I assume the formatting is wrong.

2024-10-03 14:12 UTC, Tomas2D commented on src/adapters/shared/llmChatTemplates.ts
> +{{assistant}}<|eot_id|>{{/assistant}}{{/messages}}<|start_header_id|>assistant<|end_header_id|>
Why are you editing llama3?

2024-10-03 14:12 UTC, Tomas2D commented on src/adapters/shared/llmChatTemplates.ts
>  {{user}}<|eot_id|>{{/user}}{{#assistant}}<|start_header_id|>assistant<|end_header_id|>
I assume the formatting is wrong.

2024-10-03 14:12 UTC, Tomas2D commented on src/adapters/watsonx/chatPreset.ts
> +  "meta-llama/Llama-3.2-3B-Instruct": (): WatsonXChatLLMPreset => {
Wrong name.

2024-10-21 22:20 UTC, Tomas2D commented
I am closing this for being stale.

2024-10-21 22:20 UTC, closed without merging