feat(observe): implement observe connector
i-am-bee/bee-agent-framework pull request #75
Opened 2024-10-10 08:30 UTC by GALLLASMILAN

### Which issue(s) does this pull-request address?

Closes: https://github.ibm.com/Incubation/bee-observe/issues/8

### Description

I implemented the `bee-observe-connector` directly into the framework. We have to to wait for the [bee-observe](https://github.ibm.com/Incubation/bee-observe) and [bee-observe-connector](https://github.ibm.com/Incubation/bee-observe-connector) to be public

### Checklist

- [x] I have read the [contributor guide](https://github.com/i-am-bee/bee-agent-framework/blob/main/CONTRIBUTING.md)
- [x] Linting passes: `yarn lint` or `yarn lint:fix`
- [x] Formatting is applied: `yarn format` or `yarn format:fix`
- [x] Unit tests pass: `yarn test:unit`
- [x] E2E tests pass: `yarn test:e2e`
- [ ] Tests are included **No code changes**
- [x] Documentation is changed or added
- [x] Commit messages and PR title follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2024-10-10 09:28 UTC, Tomas2D requested changes

2024-10-10 09:28 UTC, Tomas2D commented on .gitignore
> +trace.json
Use `/examples/tmp/observability/trace.json` to save the trace.

And add this line to the `.gitignore`

```
/examples/tmp/observability/*
```

2024-10-10 09:28 UTC, Tomas2D commented on README.md
> +➡️ See the [Observe API / mlflow example](./examples/agents/bee_observe.ts).
`MLFlow`

2024-10-10 09:28 UTC, Tomas2D commented on README.md
> +#### Observe / mlflow
`MLFlow` (add link to the MLFlow)

2024-10-10 09:28 UTC, Tomas2D commented on README.md
> +2. Start the agent using the observe and mlflow `yarn start:observe` (it runs ./examples/agents/bee_observe.ts file).
add link to the file

2024-10-10 09:28 UTC, Tomas2D commented on docker-compose.yml
> +    image: mongo:7
I would pin a version.

2024-10-10 09:28 UTC, Tomas2D commented on docs/templates.md
I will fix this on the main branch.

2024-10-10 09:28 UTC, Tomas2D commented on package.json
> +    "bee-agent-framework": "^0.0.26",
Remove.

2024-10-10 09:28 UTC, Tomas2D commented on package.json
> +    "bee-observe-connector": "^0.0.2",
This is a peer dependency and a dev dependency.

2024-10-10 09:28 UTC, Tomas2D commented on examples/agents/bee_observe.ts
> +              console.log(ObserveError.ensure(err).explain());
use reader

2024-10-10 09:28 UTC, Tomas2D commented on infra/observe/entrypoint.sh
> +# Create experiment directory and ensure it has the correct permissions
add `set -e` to fail fast

2024-10-10 09:28 UTC, Tomas2D commented on package.json
> +    "start:observe": "yarn start -- examples/agents/bee_observe.ts",
`start:bee_observe`

2024-10-10 13:59 UTC, GALLLASMILAN commented on infra/observe/entrypoint.sh
> +# Create experiment directory and ensure it has the correct permissions
done

2024-10-14 10:12 UTC, Tomas2D commented
Let's move this to https://github.com/i-am-bee/bee-agent-framework-starter.

2024-10-14 10:12 UTC, closed without merging